source 'https://github.com/CocoaPods/Specs.git'
target 'MMDA' do
  use_frameworks!  
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Charts'
  pod 'PusherSwift', '~> 4.1.0'
  pod 'Alamofire', '~>4.4.0'
end